services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5433:5432
    env_file:
      - ./blogify-back/.env.test

  node:
    container_name: node
    build: ./blogify-back
    ports:
      - 4000:4000
    depends_on:
      - postgres
    env_file:
      - ./blogify-back/.env.test