services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5433:5432
    env_file:
      - blogify-back/.env
    volumes:
      - postgres-volume:/var/lib/postgresql/data

  node:
    container_name: node
    build: ./blogify-back
    ports:
      - 4000:4000
    depends_on:
      - postgres
    env_file:
      - blogify-back/.env

  react:
    container_name: react
    build: ./blogify-front
    volumes:
      - react-volume:/var/www/html

  nginx:
    container_name: nginx_app
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - react-volume:/var/www/html
    depends_on:
      - postgres
      - node
      - react

volumes:
  postgres-volume:
  react-volume: